# Generated by Django 4.0.4 on 2022-06-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
