# Generated by Django 4.0.4 on 2022-06-15 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0004_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_operation', to='dataapp.post')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
